name: CI
on:
  pull_request:
  push:
    branches: ["**"]
  workflow_dispatch:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Backend deps
        run: |
          if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
      - name: Lint placeholder
        run: echo "ok"

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Frontend deps
        run: |
          if [ -f frontend/package.json ]; then cd frontend && npm ci || npm install; fi
      - name: Build
        run: |
          if [ -f frontend/package.json ]; then cd frontend && npm run build; fi
